version: '3.3'
services:
  database:
    image: postgres:15.4
    volumes:
       - "./sql-scripts:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_PASSWORD: password123
    ports:
      - '5432:5432'